"""empty message

Revision ID: 52effb297948
Revises: f7cb8f9bc8ab
Create Date: 2022-05-30 23:18:15.333654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52effb297948'
down_revision = 'f7cb8f9bc8ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
